### ISSUE TITLE
It just works!

### ISSUE THREAD

**Issue by MichaelVoelkel** [jahnf/lime-crypt#6]
Hi! I see that you had no watchers or followers and I do not understand why. While Crypto++ is a hassle to get working with Cmake, your project, though clearly based on Crypto++, just works fine with macOS Catalina, Xcode11.4.1.

Thanks for the effort of creating this neat package. This is not really an issue, but I wanted to drop my thanks!

**Comment by jahnf** [comment]
Thank you, appreciate it!
